<div class="share-block align-items-center text-area">
    <a href="#" class="btn curve-btn" data-trigger="reviewModaltrigger">Write a Review</a> 
	<button href="#" class="btn curve-btn mgz-faq-action-btn" id="mgz-faq-action">
        <span><?= __("Ask a question"); ?></span>
    </button>
    <span class="sharelinks mb-0"><?= __("Share This"); ?></span>
    <div class="social-links-connetc a2a_kit">
        <a class="a2a_button_whatsapp">
            <span><i class="fab fa-whatsapp"></i></span>
        </a>
        <a class="a2a_button_facebook">
            <span><i class="fab fa-facebook"></i></span>
        </a>
        <a href="#">
            <span class="st_instagram"><!-- <i class="fab fa-instagram-square"> --></i></span>
        </a>
    </div>
</div>
<!-- AddToAny BEGIN -->
<script async src="https://static.addtoany.com/menu/page.js"></script>
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript">stLight.options({publisher: "791bb30f-74a2-4e0f-bde5-5bc23d04c358", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>
<!-- AddToAny END -->