<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Newsletter\Block\Subscribe $block */

$objectManager =  \Magento\Framework\App\ObjectManager::getInstance(); 

$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$store = $storeManager->getStore();
$baseUrl = $store->getBaseUrl();
$baseSecureUrl = $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB, true);


?>

<form action="" class="sub-form mx-auto form subscribe" novalidate
	action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
	method="post"
	data-mage-init='{"validation": {"errorClass": "mage-error"}}'
	id="newsletter-validate-detail">
	
	<div class="d-flex">
	
		<input name="email" type="email" id="newsletter" class="form-control border-none"
		   placeholder="<?= $block->escapeHtmlAttr(__('Enter your email address')) ?>"
		   data-mage-init='{"mage/trim-input":{}}'
		   data-validate="{required:true, 'validate-email':true}"
		/>
		
		<button class="action subscribe primary"
				title="<?= $block->escapeHtmlAttr(__('Send')) ?>"
				type="submit"
				aria-label="Subscribe">
			<span><img src="<?php echo $baseUrl; ?>/images/enter-icon.png" alt="icon"></span>
		</button>
		
	</div>
	
</form>

<?php /* ?>
<div class="block newsletter">
    <div class="title"><strong><?= $block->escapeHtml(__('Newsletter')) ?></strong></div>
    <div class="content">
        <form class="form subscribe"
            novalidate
            action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
            <div class="field newsletter">
                <div class="control">
                    <label for="newsletter">
                        <span class="label">
                            <?= $block->escapeHtml(__('Sign Up for Our Newsletter:')) ?>
                        </span>
                        <input name="email" type="email" id="newsletter"
                               placeholder="<?= $block->escapeHtmlAttr(__('Enter your email address')) ?>"
                               data-mage-init='{"mage/trim-input":{}}'
                               data-validate="{required:true, 'validate-email':true}"
                        />
                    </label>
                </div>
            </div>
            <div class="actions">
                <button class="action subscribe primary"
                        title="<?= $block->escapeHtmlAttr(__('Send')) ?>"
                        type="submit"
                        aria-label="Subscribe">
                    <span><?= $block->escapeHtml(__('Send')) ?></span>
                </button>
            </div>
        </form>
    </div>
</div><?php */ ?>
