<?php
/**
 * Magedelight
 * Copyright (C) 2016 Magedelight <info@magedelight.com>
 *
 * NOTICE OF LICENSE
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see http://opensource.org/licenses/gpl-3.0.html.
 *
 * @category Magedelight
 * @package Magedelight_ScheduleShipping
 * @copyright Copyright (c) 2016 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
?>
<div class="userguide-container" style="border:dotted 1px #ccc; padding:20px;">


    <div id="messages">
        <ul class="messages">
            <li class="message message-notice notice" style="list-style: none;">
                <ul>
                    <li style="list-style: none;">For custom theme User:</li>
                </ul>
            </li>
        </ul>
    </div>



    <pre>
<code><strong>File Path:</strong> app\code\Magedelight\OneStepCheckout\view\frontend\layout\onestepcheckout.xml</code>
<code>
 If you are facing issue related to deteriorate styles and you have installed custom theme then some of theme providers remove default styles of Magento,<br> In that case please go to the above path and uncomment included style "md-onestepcheckout.css" from the head tag.


</code>
    </pre>
 
</div>
