<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_Amp
 */
?>
<?php
/* @var $block \Amasty\Amp\Block\Product\Content\View\Options */

$options = $block->decorateArray($block->getOptions())
?>

<?php if (count($options)):?>
    <?php foreach ($options as $option): ?>
        <?= $block->getOptionHtml($option) ?>
    <?php endforeach; ?>

    <?php if ($block->getIsNotAllOptionsAvailable()):?>
        <input type="hidden" name="amamp_option_flag" value="1" />
    <?php endif; ?>
<?php endif; ?>
