<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_Amp
 */
?>
<?php
/**
 * @var $block \Magento\Theme\Block\Html\Title
 */

$specialAttr = $block->getAddBaseAttributeAria() ? 'aria-labelledby="' . $block->getAddBaseAttributeAria() . '"' : '';
$title = trim($block->getPageHeading()) ? $block->getPageHeading() : '';
?>

<?php if ($title): ?>
    <h1 class="amamp-title" <?= /* @noEscape */ $specialAttr ?>>
        <?= $block->escapeHtml($title) ?>
    </h1>
<?php endif; ?>
