<?php

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * /** @var $config \Magento\Swatches\Block\Product\Renderer\Listing\Configurable */
 
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_data_helper = $this->helper('Lof\QtyDropdown\Helper\Data');
$_config_helper = $this->helper('Lof\QtyDropdown\Helper\Config');
$page = 'category';
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
		<div class="list-row">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product):
                
                ?>

            
            
            <li class="item product product-item">
                <div class="product-item-info" data-container="product-<?= /* @escapeNotVerified */ $viewMode ?>">
                    <?php
                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
					<div class="pro-img">
                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>
					</div>	
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </strong>
                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
                        <?= $block->getProductDetailsHtml($_product) ?>
                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                    <?php if ($_product->isSaleable() || ($enable_addtoquote_nonsale && !$_product->isSaleable())): ?>
                                    <form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="product_addtocart_form_<?php echo $_product->getId(); ?>">
                                        
                                        <?php
                                        if($_product->getTypeId() == "configurable"){
                                            $bar = array();
                                            $foo = "";
                                            // $configurable = $config->getJsonConfig();
                                            $configurable = $_config_helper->getJsonConfig($_product);
                                            // echo $_config_helper->getJsonConfigurable($_product);die;
                                            $format = json_decode($configurable)->priceFormat;
                                            $attribute = json_decode($configurable)->attributes;
                                            $hideDropdown = true;
                                            echo $_data_helper->showDropdown($_product,$block,$page,$hideDropdown);
                                            $data_role = 'swatch-options';
                                            $index = (json_decode($configurable,true)['index']);
                                            $optionPrice = json_decode($configurable,true)['optionPrices'];
                                            $conf = [];
                                            foreach($index as $key =>$a){
                                                foreach($optionPrice as $k => $val){
                                                    if($k == $key){
                                                        $b = $a + $val;
                                                        array_push($conf,$b);
                                                    }
                                                }
                                            }
                                            $index = json_encode($conf);
                                            // var_dump($index);
                                            ?>
                                            <script type="text/x-magento-init">
                                            {
                                                ".product-item-info": {
                                                    "Lof_QtyDropdown/js/bundle": {
                                                        "optionMap":<?php echo json_encode($attribute) ?>,
                                                        "producttype": "<?php echo $_product->getTypeId() ?>",
                                                        "limit": <?php echo $_data_helper->getMaxQtyStep(); ?>,
                                                        "format": <?php echo json_encode($format); ?>,
                                                        "tierPrices": <?php echo json_encode($foo);?>,
                                                        "finalPrice": <?php echo $_product->getFinalPrice(); ?>,
                                                        "page":"list",
                                                        "optTmpl": "<?php echo $_data_helper->getConfigValue('option_template'); ?>",
                                                        "optTmplMulti": "<?php echo $_data_helper->getConfigValue('option_template_multi'); ?>",
                                                        "optTmplTier": "<?php echo $_data_helper->getConfigValue('option_template_tier'); ?>",
                                                        "configurable": <?php echo json_encode($configurable) ;?> 
                                                        }
                                                }
                                            }
                                            </script>
                                        <?php
                                        }
                                        else if($_product->getTypeId() == "bundle" || $_product->getTypeId() == "grouped"){
                                            //do nothing
                                        }
                                        else{
                                            $hideDropdown = true;
                                            echo $_data_helper->showDropdown($_product,$block,$page,$hideDropdown);
                                        }
                                        ?>
                                        <button type="submit"
                                                title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                class="action tocart primary">
                                            <span><?php /* @escapeNotVerified */
                                                echo __('Add to Cart') ?></span>
                                        </button>
                                    
                                    </form>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span><?php /* @escapeNotVerified */
                                                    echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */
                                                    echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */ $_productNameStripped ?>"
                                       class="action more"><?= /* @escapeNotVerified */ __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </li>
            
            <?php endforeach; ?>
        </ol>
		</div>
	</div>
	<div class="bottom-toolbar">
    	<?= $block->getToolbarHtml() ?>
	</div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>

