<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_Amp
 */
?>
<?php
/**
 * @var Amasty\Amp\Block\Cms\Widget\ProductLink $block
 *
 * Amp widget template for link type inline
 */
?>

<a class="amamp-link -inline"
   href="<?= $block->escapeHtmlAttr($block->getHref()); ?>"
   aria-label="<?= $block->escapeHtmlAttr($block->getTitle()); ?>">
    <?= $block->escapeHtml($block->getLabel()); ?>
</a>
