<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php
    $_category  = $block->getCurrentCategory();

	$html=$this->getLayout()
		->createBlock('Magento\Cms\Block\Block')
		->setBlockId('category-slider-'.$_category->getId())
		->toHtml();
	if(!$html){
			$html=$this->getLayout()
		->createBlock('Magento\Cms\Block\Block')
		->setBlockId('category-slider-default')
		->toHtml();
		}
	?>
	<div class="category-slider">
		<?php echo $html; ?>
	</div>