<?php
$baseHelper = $this->helper('ET\Base\Helper\Data');
$baseUrl = $this->getBaseUrl();
$headerStaticBlock = $baseHelper->getConfigValue('header_section/general/header_static_block');
?>
<?php /*echo $this->getChildHtml("et.top.promotion");*/ ?>


<div class="top-header">
    <div class="custom-container alignment">
	
		<?php
        if ($headerStaticBlock != '') {
            echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($headerStaticBlock)->toHtml();
        }
        ?>
		
		<?php /*echo $this->getChildHtml("skip_to_content"); ?>
		<?php echo $this->getChildHtml("store_language"); ?>
		<?php echo $this->getChildHtml("currency"); ?>
		<?php echo $this->getChildHtml("header.links"); */?>
        
    </div>
</div>

<header class="main-header">
   

    <div class="custom-container">
        <div class="d-flex align-items-center justify-content-between">
            <div class="left-side-icons">
                <a href="javascript:void(0)"><i class="fas fa-search for-desk"></i></a>
                <div class="burger-menu">
                    <div></div>
                    <div></div>
                    <div></div>
                </div>
            </div>
            <div class="search-fied">
                <form action="<?php echo $baseUrl; ?>/catalogsearch/result/" method="get">
				
					<input id="search" type="text" name="q" value="" placeholder="Search entire store here..." class="form-control" maxlength="128" role="combobox" aria-haspopup="false" aria-autocomplete="both" autocomplete="off" aria-expanded="false">					
                    <input type="submit" value="" class="">
                    <span class="close-search"><i class="fas fa-times ml-2"></i></span>
                </form>
            </div>
            <div class="header-menu-center d-flex justify-content-between align-items-center">
               
                <div class="main-logo ml-3 mr-3">
                    <?php echo $this->getChildHtml("logo"); ?>
                </div>
                
            </div>
            <div class="right-side-icons ">
			
				<div class="dropdown d-inline">
					<a class="dropdown-toggle user-desk" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<i class="far fa-user"></i>
					</a>

					<div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
						<?php echo $this->getChildHtml('header.links'); ?>
					</div>
				</div>
				
                <a href="javascript:void(0)" class="search-mob"><i class="fas fa-search"></i></a>
				
				<?php echo $this->getChildHtml('minicart'); ?>
				
               
            </div>
        </div>
    </div>
</header>

<div class="mobile-search">
    <div class="search-box d-flex align-items-center">
        <div class="search d-flex align-items-center">
            <span><i class="fas fa-search"></i></span>
			
			<form action="<?php echo $baseUrl; ?>/catalogsearch/result/" method="get">			
				<input id="search" type="text" name="q" value="" placeholder="Search entire store here..." class="search-input" maxlength="128" role="combobox" aria-haspopup="false" aria-autocomplete="both" autocomplete="off" aria-expanded="false">					
				<input type="submit" value="" class="">
			</form>
			
        </div>
        <span class="cancel">Cancel</span>
    </div>
    <div class="background-blur">
    </div>
</div>



<?php /**/ ?>
<header class="page-header type1 text-center">
    <?php /* ?><div class="panel wrapper">
        <div class="panel header">
            <?php echo $this->getChildHtml("skip_to_content"); ?>
            <?php echo $this->getChildHtml("store_language"); ?>
            <?php echo $this->getChildHtml("currency"); ?>
            <?php echo $this->getChildHtml("header.links"); ?>
        </div>
    </div><?php */ ?>
    <?php /* ?><div class="header content">
        <div class="header-logo">
            <?php echo $this->getChildHtml("logo"); ?>
        </div>
        <?php echo $this->getChildHtml("minicart"); ?>
        <?php
        if ($headerStaticBlock != '') {
            echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($headerStaticBlock)->toHtml();
        }
        ?>
        <?php echo $this->getChildHtml("top.search"); ?>
    </div><?php /**/ ?>
    <?php echo $this->getChildHtml("navigation.sections"); ?>
</header><?php /**/ ?>

<script>
require(['jquery', 'jquery/ui'], function($){
	$(document).ready(() => {
		jQuery('.burger-menu').on('click', () => {
			jQuery('.left-side-menu-mob').css({
				'left': '0',
			})
		});

		jQuery('.close-btn').on('click', () => {
			jQuery('.left-side-menu-mob').css({
				'left': '-300px',
			})
		});


		jQuery('.left-side-icons a .fa-search').on('click', () => {
			jQuery('.search-fied').css({
				'width': '85%',
			});
		})

		jQuery('.close-search').on('click', () => {
			jQuery('.search-fied').css({
				'width': '0',
			});
		})

		jQuery('.search-mob').on('click', () => {
			jQuery('.mobile-search').toggle();
		})

		jQuery('.cancel').on('click', () => {
			jQuery('.mobile-search').toggle();
		})
	});
});
</script>

