<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');//get current product
$product_id =  $product->getId();

$product = $objectManager->create("Magento\Catalog\Model\Product")->load($product_id);

$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currentStoreId = $storeManager->getStore()->getId();

$reviewCollectionFactory = $objectManager->create('Magento\Review\Model\ResourceModel\Review\CollectionFactory')->create();
$reviewsCollection = $reviewCollectionFactory->addFieldToSelect('*')
        ->addStoreFilter($currentStoreId)
        ->addStatusFilter(\Magento\Review\Model\Review::STATUS_APPROVED)
        ->addEntityFilter(
            'product',
            $product_id
        )->setDateOrder()
        ->addRateVotes();
$show_review = false;
if(sizeof($reviewsCollection->getData()) > 0){
    $show_review = true;
}

$avgRatingArray = array();
foreach($reviewsCollection as $review){
    $countRatings = count($review->getRatingVotes());
    if ($countRatings > 0) {
        $allRatings = 0;
        foreach ($review->getRatingVotes() as $vote) {
            $allRatings = $allRatings + $vote->getPercent();
        }
        $allRatingsAvg = $allRatings / $countRatings;
        $avgRatingArray[] = $allRatingsAvg;
    }
}
// print_r($avgRatingArray);

$total = 0;
$reviewCount = 0;
$rateSummary = 0;

if(count($avgRatingArray)>0){
	$total = array_sum($avgRatingArray);
	$reviewCount = count($avgRatingArray);
	$rateSummary = $total / $reviewCount;
}

?>
<div class="review-block align-items-center text-area">
  <div class="row">
	<div class="col-md-8 pr-0">
	  <div class="d-flex"> <span class="mn-0">Rate the product</span>
		<div class="rating-summary">
		  <div class="rating-result" title="<?php echo $rateSummary;?>%"> <span style="width: <?php echo $rateSummary;?>%;"> <span> <span itemprop="ratingValue"><?php echo $rateSummary;?></span>% of <span itemprop="bestRating">100</span> </span> </span> </div>
		</div>
	  </div>
	  <div class="clearfix"></div>
	  <span class="mn-0">Product Review</span> <span class="mn-0 numbers-review"><?php echo number_format($reviewCount); ?></span> </div>
	<div class="col-md-4 pl-1"> </div>
  </div>
</div>

