<?php
/**
 *
 * (Load html for shipment creation)
 * popup
 */
?>
<?php 
$orderid = $this->getRequest()->getParam('order_id');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$order = $objectManager->create('Magento\Sales\Api\Data\OrderInterface')->load($orderid);
?>
<div id="ship_overlay">
    <div id="shipment_creation">
        <div class="blurdart_order_shipment_logo" >&emsp;</div>		
        <form id="blurdart_order_shipment" name="blurdart_order_shipment" method="post" action="<?php echo $this->getUrl('bluedart/shipment/sendshipment', ['order_id' => $this->getOrder()->getId()]); ?>" enctype="multipart/form-data">
            <input type="hidden" name="shipment_referer" value="<?php echo $this->getCurrentUrl(); ?>" />
            <?php echo $this->getBlockHtml('formkey') ?>
            <input name="order_id" type="hidden" value="<?php echo $this->getRequest()->getParam('order_id') ?>" />
            <?php
                if ($this->getOrder()->canShip() && !$this->getOrder()->getForcedShipmentWithInvoice()){
            ?>
                <div class="text_short" style="float: left; width: 25%;">
                    <label><?php echo __('Create Shipment') ?></label>
                    <select name="shiporder">
                        <option value="no"><?php echo __("No"); ?></option>
                        <option value="yes"><?php echo __("Yes"); ?></option>
                    </select>
                    <br/>
                    <small>If selected 'Yes' then order shipment will be created with order items, and will be mail to customer with shipment Tracking Id and Shipment Name as 'Bluedart'</small>
                </div>
            <?php } ?>
            <fieldset class="shipment_creation_fieldset" id="MyBShipModel_body">
                <legend>Packing Box Dimension </legend>
                <div class="error_flex"></div>
                <div id="receiver_details" class="shipment_creation_part">
                    <?php
                    $helper = $this->helper('Softprodigy\Bluedart\Helper\Data');
                    $defaultCode = $helper->getStoreConfig('Softprodigy_Bluedart/general/product_code');
                    ?>
                    <div class="text_short">
                        <label><?php echo __('Shipment Mode') ?> (<?php echo __("Shipment Mode") ?>)</label>
                        <select name="shipmode">
                            <option value="A" <?php echo $defaultCode=='A'? ' selected="selected" ': ''; ?>><?php echo __("Air"); ?></option>
                            <option value="E" <?php echo $defaultCode=='E'? ' selected="selected" ': ''; ?>><?php echo __("Surface"); ?></option>
                        </select>
                    </div>
                    <div class="text_short">
                        <label><?php echo __('Breadth') ?> (<?php echo __("In cm") ?>)</label>
                        <input id="breadth" data-title="<?php echo __('Breadth') ?>" name="shipment[breadth]" type="text" min="1" onchange="validateNonNegative(this);" onkeyup="validateNonNegative(this);" onpaste="validateNonNegative(this);" class="input-text required-entry validate-number" />
                    </div>
                    <div class="text_short">
                        <label><?php echo __('Height') ?> (<?php echo __("In cm") ?>)</label>
                        <input id="height" data-title="<?php echo __('Height') ?>" name="shipment[height]" onchange="validateNonNegative(this);" onkeyup="validateNonNegative(this);" onpaste="validateNonNegative(this);" type="text"  min="1" class="input-text required-entry validate-number" />
                    </div>
                    <div class="text_short">
                        <label><?php echo __('Length') ?> (<?php echo __("In cm") ?>)</label>
                        <input id="length" data-title="<?php echo __('Length') ?>" name="shipment[length]" type="text" onchange="validateNonNegative(this);" onkeyup="validateNonNegative(this);" onpaste="validateNonNegative(this);"  min="1" class="input-text required-entry validate-number" />
                    </div>
                    <div class="text_short">
                        <label><?php echo __('Weight') ?> <span style="color:#f00;">(<?php echo __("In Kg") ?>)</span></label>
                        <input id="weight" data-title="<?php echo __('Weight') ?>" onchange="validateNonNegative(this);" onkeyup="validateNonNegative(this);" onpaste="validateNonNegative(this);" name="shipment[weight]" type="text" class="input-text required-entry validate-number" />
                    </div>
                    <label>
                        <strong><?php echo __('Actual Weight (in kg)') ?><br/>
                            <label class="weight_converted"></label> (kg)
                        </strong>
                    </label>
                    <?php if(count($order->getAllVisibleItems()) > 1){ ?>
                    <div class="order_items_checkbox">
						<h2>Select products to generate AWB</h2><span class="span_note">Note: unselected products will be added in other AWB.</span>
					<ul class="checkboxes">
					<?php foreach ($order->getAllVisibleItems() as $item): ?>
						<li>
							<label for="check-<?php echo $item->getId()?>"><?php echo $item->getName()."(".$item->getSku().")"; ?>
							</label><input id="check-<?php echo $item->getId()?>"type="checkbox" value="<?php echo $item->getId()?>" name="order_items[]"/>
						</li>
					<?php endforeach;?>
					</ul></div>
					<?php }?>
                </div>
                
            </fieldset>
            
            <div class="clearer"></div>

            <!--		<button id="shipment_creation_submit_id" type="submit" name="shipment_creation_submit_id">Submit Shipment</button>
                            <button onclick="getclose()" type="button">Close</button>-->
        </form>
    </div>
</div>
<!--<script src="https://code.jquery.com/ui/1.10.0/jquery-ui.js"></script>
<link rel="stylesheet" href="https://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css" />
<script type="text/javascript" src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.10.0/jquery.validate.min.js"></script>-->
<style>
    .order-payment-additional #ship_overlay{
        display: none;
    }
   .order_items_checkbox  .checkboxes li {
    list-style: none;
    float: left;
    width: 100%;
    margin: 0 0 10px;
}
.order_items_checkbox .checkboxes li input {
    vertical-align: top !important;
    float: left !important;
    margin: 0 10px 0 0 !important;
    height: auto !important;
    line-height: 0 !important;
    width: auto !important;
    display: inline-block !important;
}
.order_items_checkbox h2{margin-top: 20px;margin-bottom: 4px;font-weight: bold;}
.span_note{margin-bottom: 20px;display: block;}
</style>
<script>
	require([
        'jquery'
    ], function ($) {
		$('#weight').keyup(function() {
		var dInput = this.value;
		var f_weight = (parseFloat(dInput)/1000).toFixed(4);
		if(f_weight != "NaN"){
			$(".weight_converted").html(f_weight);
		}
		else{
			$(".weight_converted").html("");
		}
	});
	});
    /*require([
        'ko',
        'jquery'
    ], function (ko, $) {
        function MyBShipModel(jquery) {
            this.actShipWeight = ko.observable('');
            this.shipWeight = ko.pureComputed({
                read: function () {
                    return '';
                },
                write: function (value) {
                    if(value==='' || value<0)
                        value = 0;
                    
                    if (value > 0) { // Ignore values with no space character
                        this.actShipWeight((parseFloat(value)/1000).toFixed(4));
                        jQuery('#weight').val(Math.floor(value));
                    }
                },
                owner: this
            });
        }
        var bele = document.getElementById("MyBShipModel_body");
        ko.cleanNode(bele);
        ko.applyBindings(new MyBShipModel($), bele);
    });*/
</script>
