<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_Rma
 */
?>
<?php /** @var \Amasty\Rma\Block\Adminhtml\Advertising $block */ ?>

<div class="amrma-advertising-banner">
    <div class="message">
        <p>
            <?= /** @escapeNotVerified */ __('In case you need to export more order entities for detailed reports '
                . 'or to schedule export in profiles to another server or directory, learn how to do it with '
                . '<a href="' . $block->getLink() . '" target="_blank">Export Orders</a>.') ?>
        </p>
    </div>
</div>
