<?php
    /** @var \Meetanshi\MaintenancePage\Block\Index $block */
    $helper = $block->getHelper();
?>
<?php if ($helper->isGoogleAnalyticsEnabled()) : ?>
    <?php $trackingId = $helper->getGoogleAnalyticsTrackingId(); ?>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script type="text/javascript" async src="https://www.googletagmanager.com/gtag/js?id=<?=$trackingId?>"></script>
    <script type="text/javascript">
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', '<?=$trackingId?>');
    </script>
<?php endif; ?>
