<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_Rma
 */
?>
<?php
/**
 * @var \Amasty\Rma\Block\Returns\History $block
 */

if ($history = $block->getProceedData()): ?>
    <div class="amrma-table-container">
        <div class="table-wrapper returns-history" style="display: none;">
            <table class="data table table-returns-items history amrma-table" id="my-returns-table">
                <caption class="table-caption"><?= $block->escapeHtml(__('Returns')) ?></caption>
                <thead>
                <tr>
                    <th scope="col" class="col id"><?= $block->escapeHtml(__('Items')) ?></th>
                    <th scope="col" class="col shipping"><?= $block->escapeHtml(__('Qty')) ?></th>
                    <th scope="col" class="col id"><?= $block->escapeHtml(__('Id')) ?></th>
                    <th scope="col" class="col date"><?= $block->escapeHtml(__('Date')) ?></th>
                    <th scope="col" class="col total"><?= $block->escapeHtml(__('Order #')) ?></th>
                    <th scope="col" class="col status"><?= $block->escapeHtml(__('Status')) ?></th>
                    <th scope="col" class="col actions"></th>
                </tr>
                </thead>
                <tbody class="amrma-tbody">
                <?php foreach ($history as $item): ?>
                    <tr class="amrma-row">
                        <td data-th="<?= $block->escapeHtml(__('Item')) ?>" class="col item">
                            <div class="amrma-image<?= ($block->isChatEnabled() && !empty($item['new_message']) ? ' new-message' : ''); ?>"><img src="<?= $block->escapeUrl($item['product_url'])?>"/></div>
                        </td>
                        <td data-th="<?= $block->escapeHtml(__('Qty')) ?>" class="col qty"><?= (double)$item['qty']; ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Id')) ?>" class="col id"><?= $block->escapeHtml($item['request_id'])?></td>
                        <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date"><?= $block->escapeHtml($block->formatDate($item['created_at'])) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="col order"><?= $block->escapeHtml(str_pad($item[\Magento\Sales\Api\Data\OrderInterface::INCREMENT_ID], 9, '0', STR_PAD_LEFT)) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status">
                        <span class="amrma-status -pending"<?= (!empty($item['status_color'])?' style="background-color: ' . $block->escapeHtml($item['status_color']) . '"':'') ?>>
                            <?= $block->escapeHtml($item['status_label']) ?>
                        </span>
                        </td>
                        <td class="col actions">
                            <a href="<?= $block->escapeUrl($item['view_url']); ?>" class="action view" title="<?= $block->escapeHtml(__('View')) ?>">
                                <?= $block->escapeHtml(__('View')) ?>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <?php foreach ($history as $item): ?>
            <?php

                $helper = $this->helper("Papa\CodTwoFactor\Helper\Data");
                $orderItem = $helper->getOrderItem($item['item_id']);
                $itemName = $orderItem->getName();
                $itemPrice = $this->helper('Magento\Framework\Pricing\Helper\Data')->currency(number_format($orderItem->getPriceInclTax(),2),true,false);

            ?>
            <div class="order-sec">
                <div class="row">
                    <div class="col-md-12 no-border"> 
                        <span class="ordr-id"><?= $block->escapeHtml(__('Order ID')) ?>: <?= $block->escapeHtml(str_pad($item[\Magento\Sales\Api\Data\OrderInterface::INCREMENT_ID], 9, '0', STR_PAD_LEFT)) ?></span>
                        <span class="pull-right"><?= $block->escapeHtml($block->formatDate($item['created_at'])) ?></span>
                    </div>
                    <div class="col-md-2 no-border">
                        <img src="<?= $block->escapeUrl($item['product_url'])?>"  class="img-fluid mt-2 d-block"/>
                    </div>
                    <div class="col-md-5 desc-sec no-border pt-2">
                        <h1><?= $itemName; ?></h1>
                        <h2><?= __("Rs. "); ?><span class="price"><?= $itemPrice; ?></span></h2>
                        <h3><?= $block->escapeHtml(__('Qty')) ?>: <span><?= (double)$item['qty']; ?></span></h3>
                    </div>
                    <div class="col-md-2 no-border pl-0 pr-0  pt-2"><span class="font-regular"><?= $block->escapeHtml(__('Status')) ?></span><br><span class="mud-colour"><?= $block->escapeHtml($item['status_label']) ?></span></div>
                    <div class="col-md-3 no-border pt-2">
                        <span class="font-regular d-block"><?= $block->escapeHtml(__('Delivery Expected by ')); ?><br> <?= date('d F Y'); ?></span>
                    </div>
                </div>
                <div class="arrow-order">
                    <a href="<?= $item['view_url']  ?>"><i class="sl-icon-arrow-right"></i></a>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <?php if ($pager = $block->getPagerHtml()): ?>
        <!-- <div class="toolbar">
            <div class="amasty-rma-pager"><?= /** @noEscape */ $pager; ?></div>
        </div> -->
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><?= $block->escapeHtml(__('You have placed no return request.')) ?></div>
<?php endif ?>
