<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); //instance of\Magento\Framework\App\ObjectManager
$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
$currentStore = $storeManager->getStore();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
/** @var \Magento\Customer\Block\Account\Dashboard\Address $block */
?>
        <div class="new-dashboard-sec">
            <div class="row">
                <div class="col-lg-4 col-md-6">
                    <a class="categories-item" href="/sales/order/history/">
                        <div class="icon-part">
                            <img src="<?php echo $mediaUrl ?>account/dashboard-icons/1.png" alt="">
                        </div>
                        <div class="content-part">
                            <h4 class="title">Orders</h4>
                            <span class="courses">Track your orders and returns</span>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-md-6">
                    <a class="categories-item" href="/customer/account/edit/">
                        <div class="icon-part">
                            <img src="<?php echo $mediaUrl ?>account/images/dashboard-icons/2.png" alt="">
                        </div>
                        <div class="content-part">
                            <h4 class="title">Account</h4>
                            <span class="courses">Edit your profile and login
                                information</span>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-md-6">
                    <a class="categories-item" href="/wishlist/">
                        <div class="icon-part">
                            <img src="<?php echo $mediaUrl ?>account/images/dashboard-icons/3.png" alt="">
                        </div>
                        <div class="content-part">
                            <h4 class="title">Wishlist</h4>
                            <span class="courses">View items added to your wishlist</span>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-md-6">
                    <a class="categories-item" href="/customer/address/">
                        <div class="icon-part">
                            <img src="<?php echo $mediaUrl ?>account/images/dashboard-icons/4.png" alt="">
                        </div>
                        <div class="content-part">
                            <h4 class="title">Addresses</h4>
                            <span class="courses">Edit or add new addresses</span>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-md-6">
                    <a class="categories-item" href="/newsletter/manage/">
                        <div class="icon-part">
                            <img src="<?php echo $mediaUrl ?>account/images/dashboard-icons/5.png" alt="">
                        </div>
                        <div class="content-part">
                            <h4 class="title">Communications</h4>
                            <span class="courses">Manage Newletter Communications</span>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-md-6">
                    <a class="categories-item" href="/contact/">
                        <div class="icon-part">
                            <img src="<?php echo $mediaUrl ?>account/images/dashboard-icons/6.png" alt="">
                        </div>
                        <div class="content-part">
                            <h4 class="title">Contact Us</h4>
                            <span class="courses">Get in touch with our representatives</span>
                        </div>
                    </a>
                </div>
            </div>
        </div>
<!-- <div class="block block-dashboard-addresses">
    <div class="block-title">
        <strong><?= $block->escapeHtml(__('Address Book')) ?></strong>
        <a class="action edit" href="<?= $block->escapeUrl($block->getAddressBookUrl()) ?>"><span><?= $block->escapeHtml(__('Manage Addresses')) ?></span></a>
    </div>
    <div class="block-content">
        <div class="box box-billing-address">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Default Billing Address')) ?></span>
            </strong>
            <div class="box-content">
                <address>
                    <?= $block->getPrimaryBillingAddressHtml() ?>
                </address>
            </div>
            <div class="box-actions">
                <a class="action edit" href="<?= $block->escapeUrl($block->getPrimaryBillingAddressEditUrl()) ?>" data-ui-id="default-billing-edit-link"><span><?= $block->escapeHtml(__('Edit Address')) ?></span></a>
            </div>
        </div>
        <div class="box box-shipping-address">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Default Shipping Address')) ?></span>
            </strong>
            <div class="box-content">
                <address>
                    <?= $block->getPrimaryShippingAddressHtml() ?>
                </address>
            </div>
            <div class="box-actions">
                <a class="action edit" href="<?= $block->escapeUrl($block->getPrimaryShippingAddressEditUrl()) ?>" data-ui-id="default-shipping-edit-link"><span><?= $block->escapeHtml(__('Edit Address')) ?></span></a>
            </div>
        </div>
    </div>
</div> -->
