<?php
// @codingStandardsIgnoreFile

/* @var $block \Aheadworks\Raf\Block\Advocate\ShareService */
?>
<div data-role="aw-raf-advocate-share-service"  data-bind="scope: 'aw_raf_share_service'">
    <?php /* @noEscape */ echo $block->getChildHtml(); ?>
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "[data-role=aw-raf-advocate-share-service]": {
            "Magento_Ui/js/core/app": <?php /* @noEscape */ echo $block->getJsLayout();?>
        }
    }
</script>